package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
      io.alfanhui.new_geolocation.NewGeolocationPlugin.registerWith(shimPluginRegistry.registrarFor("io.alfanhui.new_geolocation.NewGeolocationPlugin"));
      io.intheloup.streamschannel.StreamsChannelPlugin.registerWith(shimPluginRegistry.registrarFor("io.intheloup.streamschannel.StreamsChannelPlugin"));
  }
}
